version: '3.8'
services:
  nestjs-api:
    restart: always
    image: nestjs-api
    build:
      dockerfile: 'Dockerfile'
    command: sh -c "npm install && npm run start:dev"
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - /usr/src/app/node_modules
      - ./src:/usr/src/app/src
